---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: omasecure
description: Origami Linux image with Trivalent, and audio production tools.

base-image: registry.gitlab.com/origami-linux/images/origami
image-version: latest

modules:
  # Deploy system config files (sysusers.d for audio group, etc.)
  - type: files
    files:
      - source: system
        destination: /

  # Package management: add repos, install and remove packages
  #- type: script
   # scripts:
   #   - setup-tiling.sh
  - type: dnf
    repos:
      files:
        # Trivalent (hardened Chromium) and other secureblue packages
        - https://repo.secureblue.dev/secureblue.repo
      copr:
        - name: avengemedia/dms-git
          chroot: fedora-44-x86_64
        - name: avengemedia/danklinux
          chroot: fedora-44-x86_64
    install:
      packages:
        # Default browser (hardened Chromium from secureblue)
        - trivalent
        # Application launcher (Wayland-native)
        - rofi-wayland
        # Terminal emulator
        - foot
        # Screen recorder / streaming
        - obs-studio
        # Editing
        - ardour9
        - kdenlive
        #Glamour
        - gum
        - nu
        - niri
        - dms
        - dms-greeter
        - greetd
        - greetd-selinux
        - dgop
        - dsearch
    remove:
      packages:
        # Replaced by Trivalent
        - firefox
        - firefox-langpacks
        - waybar
  - type: systemd
    system:
      enabled:
        - greetd.service
      disabled:
        - cosmic-greeter.service
        - cosmic-greeter-daemon.service

  # System-wide flatpaks (Flathub)
  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.gnome.Loupe
      - scope: user

  # Signing policy for the published image
  - type: signing
