---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: omasecure
description: securbelue, and audio production tools.

base-image: ghcr.io/secureblue/sericea-main-hardened
image-version: latest

modules:
  # Deploy system config files (sysusers.d for audio group, etc.)
  - type: files
    files:
      - source: system
        destination: /

  # Package management: add repos, install and remove packages
  - type: dnf
    repos:
      copr:
        - name: atim/starship
          chroot: fedora-44-x86_64
    install:
      packages:
        # Screen recorder / streaming
        - obs-studio
        # Editing
        - ardour9
        - kdenlive
        - neovim
        #Glamour
        - gum
        - starship
        - podman-compose
  # System-wide flatpaks (Flathub)
  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - com.github.tchx84.Flatseal
          - io.github.flattool.Warehouse
          - io.missioncenter.MissionCenter
          - com.github.rafostar.Clapper
          - org.gnome.Loupe
      - scope: user

  # Signing policy for the published image
  - type: signing
