#!/bin/bash
set -euo pipefail
# Returns the battery percentage remaining as an integer
BAT_DEV=$(upower -e | grep BAT | head -n1)
[[ -z "$BAT_DEV" ]] && exit 0
upower -i "$BAT_DEV" |
  awk -F: '/percentage/ {
    gsub(/[%[:space:]]/, "", $2);
    val=$2;
    printf("%d\n", (val+0.5))
    exit
}'
